import os
import numpy as np
import pandas as pd
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
import matplotlib
matplotlib.use('Agg')

# Import project modules
import oarsi_data as p

# Configuration
CSV_PATH = "./base_stata/stataToCsvMG.csv"
OUTDIR = './results_final_analysis'
RND = 42
N_BOOT = 2000  # Number of bootstrap samples
ALPHA = 0.05   # for 95% CI

def bootstrap_or_ci(df, features, target_col='oa_knee', group_col='idelsa', n_boot=2000, alpha=0.05, seed=42):
    """
    Cluster Bootstrap for Odds Ratios.
    Resamples participants (idelsa) with replacement.
    
    Returns: DataFrame with Feature, OR, CI_Low, CI_High
    """
    print(f"Starting Cluster Bootstrap for ORs ({n_boot} iterations)...")
    rng = np.random.default_rng(seed)
    groups = df[group_col].values
    uniq_groups = np.unique(groups)
    
    # Store coefficients from each bootstrap iteration
    boot_coefs = []
    
    # Base pipeline (same as used in analysis)
    # Note: Unweighted (class_weight=None) as per final model decision
    pipe = make_pipeline(
        SimpleImputer(strategy='median'),
        StandardScaler(),
        LogisticRegression(max_iter=2000, class_weight=None)
    )
    
    for i in range(n_boot):
        if (i + 1) % 100 == 0:
            print(f"   Iteration {i + 1}/{n_boot}...", end='\r')
            
        # Resample groups
        sampled_groups = rng.choice(uniq_groups, size=len(uniq_groups), replace=True)
        
        # Create mask to select rows belonging to sampled groups
        # Since a group can be selected multiple times, we need to reconstruct the dataframe
        # This is a bit more involved than simple masking because of duplicates
        
        # Faster approach: Get indices for each group, then concatenate
        # Pre-compute group indices
        # (Optimization: could be moved outside loop if n_boot is huge, 
        # but for 2000 iter on this dataset size it's fine to be simple)
        
        # Let's map group -> indices
        # But pandas merge might be cleaner:
        # 1. Create DataFrame of sampled groups
        sampled_groups_df = pd.DataFrame({group_col: sampled_groups})
        
        # 2. Merge with original data (inner join replicates rows for repeated groups)
        # Note: 'df' must have unique index to avoid confusion, or we just ignore index
        
        # Performance trick: existing data is small enough to just concat
        # or use lookup. Let's use the merge approach for correctness with duplicates.
        boot_df = sampled_groups_df.merge(df, on=group_col, how='left')
        
        X_boot = boot_df[features]
        y_boot = boot_df[target_col]
        
        # Skip if single class in target (rare but possible in small samples)
        if y_boot.nunique() < 2:
            continue
            
        pipe.fit(X_boot, y_boot)
        model = pipe.named_steps['logisticregression']
        
        # Flatten coefs (shape 1, n_features)
        boot_coefs.append(model.coef_[0])
        
    print("\nBootstrap complete.")
    
    boot_coefs = np.array(boot_coefs) # shape (n_effective_boot, n_features)
    
    # Calculate statistics
    results = []
    for idx, feature in enumerate(features):
        coef_vals = boot_coefs[:, idx]
        
        # Point estimate (median of bootstrap distribution or re-fit on full? 
        # Standard practice: use percentiles of bootstrap distribution for CI, 
        # and point estimate from full model. OR median of bootstrap.)
        # Here we report the median of bootstrap ORs and the CI.
        
        or_vals = np.exp(coef_vals)
        or_median = np.median(or_vals)
        ci_low = np.percentile(or_vals, 100 * (alpha / 2))
        ci_high = np.percentile(or_vals, 100 * (1 - alpha / 2))
        
        results.append({
            'Feature': feature,
            'OR (Median Boot)': or_median,
            'OR 95% CI Low': ci_low,
            'OR 95% CI High': ci_high
        })
        
    return pd.DataFrame(results)

def main():
    os.makedirs(OUTDIR, exist_ok=True)
    
    # 1. Load Data
    print("Loading data...")
    df = p.load_and_prep_data(CSV_PATH, outdir=OUTDIR)
    
    # 2. Load Final Features
    # Expecting the file generated by auc_ci_bootstrap_eval.py or oarsi_analysis.py
    # If not found, we fall back to a hardcoded list or try to find it
    feature_file = os.path.join(OUTDIR, "final_5var_features_for_ci.csv")
    
    if os.path.exists(feature_file):
        print(f"Reading features from {feature_file}")
        feats_df = pd.read_csv(feature_file)
        # Assuming header 'feature' or similar single column
        if 'feature' in feats_df.columns:
            final_features = feats_df['feature'].tolist()
        else:
            final_features = feats_df.iloc[:, 0].tolist()
    else:
        print(f"Warning: {feature_file} not found. Using default clinical variables as fallback.")
        # Fallback to a reasonable set if previous step wasn't run
        final_features = ['age', 'bmi', 'sex_female'] # Placeholder, hopefully file exists
    
    print(f"Final Features for OR Calculation: {final_features}")
    
    # Filter valid features
    valid_features = [f for f in final_features if f in df.columns]
    
    if not valid_features:
        print("No valid features found in dataframe. Exiting.")
        return

    # 3. Calculate OR with Cluster Bootstrap CI
    or_df = bootstrap_or_ci(
        df, 
        valid_features, 
        target_col='oa_knee', 
        group_col='idelsa', 
        n_boot=N_BOOT, 
        alpha=ALPHA, 
        seed=RND
    )
    
    # 4. Save and Print
    out_path = os.path.join(OUTDIR, 'final_model_or_ci.csv')
    or_df.to_csv(out_path, index=False)
    
    print("\n=== FINAL MODEL STANDARDIZED ODDS RATIOS (Cluster Bootstrap 95% CI) ===")
    # Format for pretty printing
    print_df = or_df.copy()
    print_df['OR (95% CI)'] = print_df.apply(
        lambda x: f"{x['OR (Median Boot)']:.2f} ({x['OR 95% CI Low']:.2f}-{x['OR 95% CI High']:.2f})", 
        axis=1
    )
    print(print_df[['Feature', 'OR (95% CI)']].to_string(index=False))
    print(f"\nResults saved to: {out_path}")
    print("Note: ORs are standardized (per 1 SD change in the predictor).")

if __name__ == "__main__":
    main()
